{
 "title": "Cisco SNMP",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(sysName{vendor=\"cisco\"},instance)"
    }
   },
   {
    "name": "interface",
    "query": {
     "query": "label_values(ifOperStatus{instance=~\"$instance\"},ifDescr)"
    }
   },
   {
    "name": "Job",
    "query": {
     "query": "label_values(ifHCInOctets{vendor=\"cisco\"},job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Top 5 interfaces 5m",
   "type": "gauge",
   "description": "Top 5 interfaces amongst all instances",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk (5,\n((irate(ifHCInOctets{}[5m]) or irate(ifInOctets{}[5m])) + (irate(ifHCOutOctets{}[5m]) or irate(ifOutOctets{}[5m]))\n) * 8 )",
     "legendFormat": "{{instance }} {{ ifName }}"
    }
   ]
  },
  {
   "title": "Interface Status",
   "type": "gauge",
   "description": "status of all Interfaces. Controlled by job variable",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{job=~\"$Job\"}",
     "legendFormat": "{{instance}} {{ifName}}"
    }
   ]
  },
  {
   "title": "Device Status",
   "type": "stat",
   "description": "This Panel is controlled by instance variable",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 8 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=~\"$instance\"}",
     "legendFormat": "{{intance}}"
    }
   ]
  },
  {
   "title": "Device Uptime",
   "type": "stat",
   "description": "This Panel is controlled by instance variable",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=~\"$instance\"} / 8640000",
     "legendFormat": "{{instance}} Day(s)"
    }
   ]
  },
  {
   "title": "current CPU 5-min avg",
   "type": "stat",
   "description": "This Panel is controlled by instance variable",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpmCPUTotal5minRev{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} Day(s)"
    }
   ]
  },
  {
   "title": "System Information",
   "type": "table",
   "description": "Contact, Location, and description\nControlled by instance variable",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sysContact{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sysDescr{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sysLocation{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Physical Memory Usage $instance",
   "type": "gauge",
   "description": "This Panel is controlled by instance variable",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "repeat": "instance",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ciscoMemoryPoolUsed{instance=~\"$instance\", ciscoMemoryPoolType=\"1\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ciscoMemoryPoolFree{instance=~\"$instance\", ciscoMemoryPoolType=\"1\"}",
     "legendFormat": "{{instance}"
    }
   ]
  },
  {
   "title": "Interface Inventory",
   "type": "table",
   "description": "This Panel is controlled by Job variable",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifHCOutOctets{job=\"$Job\"}[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifHCInOctets{job=\"$Job\"}[$__range])",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{job=\"$Job\"}",
     "legendFormat": "high speed"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "timeseries",
   "description": "This Panel is controlled by Job variable",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "irate(ifInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In Unicast",
   "type": "timeseries",
   "description": "This Panel is controlled by Job variable",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCOutUcastPkts{job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "irate(ifHCInUcastPkts{job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In multicast",
   "type": "timeseries",
   "description": "This Panel is controlled by Job variable",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCOutMulticastPkts{job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "irate(ifHCInMulticastPkts{job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Asset Inventory",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 70 },
   "targets": [
    { "expr": "entPhysicalSerialNum", "legendFormat": "__auto" },
    { "expr": "entPhysicalModelName", "legendFormat": "__auto" },
    { "expr": "entPhysicalFirmwareRev", "legendFormat": "__auto" },
    { "expr": "entPhysicalHardwareRev", "legendFormat": "__auto" },
    { "expr": "entPhysicalSoftwareRev", "legendFormat": "__auto" }
   ]
  }
 ]
}