name: network-visualizer
services:  
  node-map:
    build: 
        context: ./scripts
        dockerfile: dockerfile
    container_name: node-map
    volumes: [./scripts:/nodemap]
    networks: ["container-network"]
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment: ["GF_INSTALL_PLUGINS=vertamedia-clickhouse-datasource"]
    expose: ["3000/tcp"]
    volumes: ["./config/grafana/provisioning:/etc/grafana/provisioning", "./config/grafana/lib:/var/lib/grafana"]
    networks: ["container-network"]

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    expose: ["9090/tcp"]
    volumes: ["./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"]
    networks: ["container-network"]

  snmp-exporter:
    image: prom/snmp-exporter:latest
    restart: unless-stopped
    expose: ["9116/tcp"]
    volumes: ["./config/snmp-exporter/snmp.yml:/etc/snmp_exporter/snmp.yml:ro"]
    command: ["--config.file=/etc/snmp_exporter/snmp.yml"]
    networks: ["container-network"]

  goflow2:
    image: netsampler/goflow2:latest
    restart: unless-stopped
    depends_on: ["kafka"]
    expose: ["6343/udp", "2055/udp", "8080/tcp"]
    command: ["-transport.kafka.brokers=kafka:9092", "-transport=kafka", "-transport.kafka.topic=flows", "-format=bin"]
    networks: ["container-network"]

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: unless-stopped
    depends_on: ["kafka"]
    environment: ["CLICKHOUSE_DO_NOT_CHOWN=1", "CLICKHOUSE_PASSWORD=visualizer"]
    expose: ["8123/tcp", "9000/tcp"]
    volumes: ["./config/clickhouse:/docker-entrypoint-initdb.d/:ro", "./config/clickhouse/flow.proto:/var/lib/clickhouse/format_schemas/flow.proto:ro", "./config/clickhouse/protocols.csv:/var/lib/clickhouse/user_files/protocols.csv:ro"]
    networks: ["container-network"]

  kafka:
    image: apache/kafka:latest
    restart: unless-stopped
    environment: ["ALLOW_PLAINTEXT_LISTENER=yes", "KAFKA_DELETE_TOPIC_ENABLE=true", "KAFKA_BROKER_ID=1", "KAFKA_NODE_ID=1", "KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093", "KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER", "KAFKA_INTER_BROKER_LISTENER_NAME=IB", "KAFKA_PROCESS_ROLES=broker,controller", "KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,BROKER:PLAINTEXT,IB:PLAINTEXT", "KAFKA_LISTENERS=CONTROLLER://:9093,BROKER://:9092,IB://:9094", "KAFKA_ADVERTISED_LISTENERS=BROKER://kafka:9092,IB://kafka:9094", "KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1"]
    expose: ["9092/tcp", "9093/tcp", "9094/tcp"]
    networks: ["container-network"]

  snmpsim:
    image: tandrup/snmpsim:latest
    restart: unless-stopped
    expose: ["161/udp"]
    volumes: ["./testing-files/snmpsim:/usr/local/snmpsim/data:ro"]
    networks: ["container-network"]
    profiles: ["test-snmp"]

  netflow-generator:
    image: networkstatic/nflow-generator:latest
    restart: unless-stopped
    depends_on: ["goflow2"]
    command: ["-t", "goflow2", "-p", "2055"]
    networks: ["container-network"]
    profiles: ["test-netflow"]

networks:
  container-network:
    driver: bridge