{
 "title": "GoFlow2 - Internal Metrics",
 "description": "GoFlow2 Internal Metrics",
 "tags": [
  "Internals",
  "GoFlow2"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Totals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NetFlows Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_process_nf_flowset_records_total[5m]))"
    }
   ]
  },
  {
   "title": "sFlows Total",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_process_sf_samples_total[5m]))"
    }
   ]
  },
  {
   "title": "Flows UDP Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "UDP2Kafka Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_traffic_bytes_total[5m])) by (remote_ip)",
     "legendFormat": "{{ remote_ip }}"
    },
    {
     "expr": "sum(rate(goflow2_flow_traffic_bytes_total[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "UDP2Kafka packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_traffic_packets_total[5m])) by (remote_ip)",
     "legendFormat": "{{ remote_ip }}"
    },
    {
     "expr": "sum(rate(goflow2_flow_traffic_packets_total[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "sFlow UDP Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_traffic_size_bytes_sum{type=\"sflow\"}[5m])) by (remote_ip)",
     "legendFormat": "{{ remote_ip }}"
    },
    {
     "aggregator": "sum",
     "alias": "$tag_type | Total",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(rate(goflow2_flow_traffic_size_bytes_sum{type=\"sflow\"}[5m]))",
     "legendFormat": "sFlow | Total",
     "tags": { "type": "sFlow" }
    }
   ]
  },
  {
   "title": "sFlow UDP Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_traffic_size_bytes_count{type=\"sflow\"}[5m])) by (remote_ip)",
     "legendFormat": "{{ remote_ip }}"
    },
    {
     "aggregator": "sum",
     "alias": "$tag_type | Total",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(rate(goflow2_flow_traffic_size_bytes_count{type=\"sflow\"}[5m]))",
     "legendFormat": "sFlow | Total",
     "tags": { "type": "sFlow" }
    }
   ]
  },
  {
   "title": "NetFlow UDP Bandwidth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_traffic_size_bytes_sum{type=\"netflow\"}[5m])) by (remote_ip)",
     "legendFormat": "{{ remote_ip }}"
    },
    {
     "expr": "sum(rate(goflow2_flow_traffic_size_bytes_sum{type=\"netflow\"}[5m]))",
     "legendFormat": "NetFlow | Total"
    }
   ]
  },
  {
   "title": "NetFlow UDP Packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_traffic_size_bytes_count{type=\"netflow\"}[5m])) by (remote_ip)",
     "legendFormat": "{{ remote_ip }}"
    },
    {
     "aggregator": "sum",
     "alias": "$tag_type | Total",
     "downsampleAggregator": "avg",
     "downsampleFillPolicy": "none",
     "expr": "sum(rate(goflow2_flow_traffic_size_bytes_count{type=\"netflow\"}[5m]))",
     "legendFormat": "NetFlow | Total",
     "tags": { "type": "NetFlow" }
    }
   ]
  },
  {
   "title": "NetFlow metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NetFlows by type and version",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_process_nf_flowset_records_total[5m])) by (version,type)",
     "legendFormat": "{{ version }} | {{ type }} "
    }
   ]
  },
  {
   "title": "NetFlows errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_process_nf_errors_total[5m])) by (error)",
     "legendFormat": "{{ error }}"
    }
   ]
  },
  {
   "title": "NetFlow templates",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_process_nf_templates_total[5m])) by (version,router,type)",
     "legendFormat": "{{ version }} | {{ router }} | {{ type }}"
    }
   ]
  },
  {
   "title": "NetFlows - DataFlowSets by router and version",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_process_nf_templates_total[5m])) by (router,version)",
     "legendFormat": "{{ router }} | {{ version }}"
    }
   ]
  },
  {
   "title": "Time between flow and processing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_process_nf_delay_seconds[5m])) by (quantile,router,version)",
     "legendFormat": "Q{{ quantile }} | {{ router }} | {{ version }}"
    }
   ]
  },
  {
   "title": "sFlow metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "targets": [
    {}
   ]
  },
  {
   "title": "sFlows by type",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_process_sf_samples_records_total[5m])) by (version,type)",
     "legendFormat": "{{ version }} | {{ type }}"
    }
   ]
  },
  {
   "title": "sFlows Flow records by agent and version",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_process_sf_samples_records_total{type=\"FlowSample\"}[5m])) by (agent,version)",
     "legendFormat": "{{ agent }} | {{ version }}"
    }
   ]
  },
  {
   "title": "NetFlow decoder metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NetFlow decoding time quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(goflow2_flow_decoding_time_seconds{name=\"netflow\"}) by (quantile)",
     "legendFormat": "Q{{ quantile }}"
    }
   ]
  },
  {
   "title": "NetFlow processing time quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(goflow2_flow_decoding_time_seconds{name=\"netflow\"}) by (quantile)",
     "legendFormat": "Q{{ quantile }}"
    }
   ]
  },
  {
   "title": "NetFlow worker rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_decoding_time_seconds{name=\"netflow\"}[5m])) by (worker)",
     "legendFormat": "Worker {{ worker }}"
    }
   ]
  },
  {
   "title": "sFlow decoder metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {}
   ]
  },
  {
   "title": "sFlow decoding time quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(goflow2_flow_decoding_time_seconds{name=\"sflow\"}) by (quantile)",
     "legendFormat": "Q{{ quantile }}"
    }
   ]
  },
  {
   "title": "sFlow processing time quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(goflow2_flow_decoding_time_seconds{name=\"sflow\"}) by (quantile)",
     "legendFormat": "Q{{ quantile }}"
    }
   ]
  },
  {
   "title": "sFlow worker rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(goflow2_flow_decoding_time_seconds{name=\"sflow\"}[5m])) by (worker)",
     "legendFormat": "Worker {{ worker }}"
    }
   ]
  }
 ]
}