{
 "title": "Host Resources",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "job", "query": { "query": "label_values(hrDeviceID,job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(hrDeviceID,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Physical Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{job=~\"$job\", instance=~\"$instance\", hrStorageDescr=\"Physical memory\"} * 100) / hrStorageSize{job=~\"$job\", instance=~\"$instance\", hrStorageDescr=\"Physical memory\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage Per Core",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrProcessorLoad{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hrSystemUptime{job=~\"$job\", instance=\"$instance\"} / 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "hrSystemProcesses{job=~\"$job\", instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Resorces",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "(hrStorageUsed{job=~\"$job\", instance=~\"$instance\", hrStorageType=\"1.3.6.1.2.1.25.2.1.4\"} * 100)/ (hrStorageSize{job=~\"$job\", instance=~\"$instance\", hrStorageType=\"1.3.6.1.2.1.25.2.1.4\"} > 0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}