{
 "title": "Snmp Dashboard r1",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Job", "query": { "query": "label_values(ifHCInOctets,job)" } },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifOperStatus,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Interface Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{job=\"$Job\"}",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Top 5 interfaces",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "topk(5, irate(ifHCInOctets{instance=\"$instance\"}[5m]) or irate(ifInOctets{instance=\"$instance\"}[5m]) or irate(ifHCOutOctets{instance=\"$instance\"}[5m]) or irate(ifOutOctets{instance=\"$instance\"}[5m]))*8",
     "legendFormat": "{{ ifName }}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "out"
    },
    {
     "expr": "irate(ifHCInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "in"
    },
    {
     "expr": "delta(ifHCOutOctets{job=\"$Job\"}[$__range])",
     "legendFormat": "total out"
    },
    {
     "expr": "delta(ifHCInOctets{job=\"$Job\"}[$__range])",
     "legendFormat": "total in"
    },
    {
     "expr": "ifHighSpeed{job=\"$Job\"}",
     "legendFormat": "high speed"
    }
   ]
  },
  {
   "title": "Out / In multicast",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCOutMulticastPkts{job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "irate(ifHCInMulticastPkts{job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In Unicast",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCOutUcastPkts{job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "irate(ifHCInUcastPkts{job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifOutOctets{job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "irate(ifInOctets{job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifOutErrors{job=\"$Job\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "irate(ifInErrors{job=\"$Job\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  }
 ]
}